name: handyman_provider_flutter
description: A new Flutter project.

publish_to: 'none'

version: 11.7.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  nb_utils: ^7.0.3
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  flutter_vector_icons: ^2.0.0
  path_provider: ^2.1.3
  dotted_border: ^2.1.0

  #Firebase
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  cloud_firestore: ^5.0.0
  firebase_pagination: ^4.0.0
  firebase_messaging: ^15.0.0

  flutter_local_notifications: ^17.1.2
  flutter_html: ^3.0.0-beta.2
  flutter_custom_tabs: ^2.0.0+1
  syncfusion_flutter_charts: ^25.2.7
  geocoding: ^3.0.0
  webview_flutter: ^4.8.0
  country_picker: ^2.0.26

  #image:
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  file_picker: ^8.0.4
  lottie: ^3.1.2

  # PAYMENTS
  midpay: ^1.1.7
  phonepe_payment_sdk: ^2.0.1
  flutter_stripe: ^10.1.1
  razorpay_flutter: ^1.3.6
#  flutterwave_standard: ^1.0.8
  cinetpay: ^1.0.7
  flutter_paypal_checkout:
    git:
      url: https://github.com/Raj-GMITS/flutter_paypal_checkout.git
      ref: main

  flutter_paystack:
    git:
      url: https://github.com/iqonic-design/flutter_paystack.git
      ref: 1.0.0

  flutter_localizations:
    sdk: flutter
  geolocator: ^12.0.0
  google_maps_flutter: ^2.2.8
  custom_map_markers: ^0.0.2+1
  permission_handler: ^11.3.1
  share_plus: ^9.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  # flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/upi_payment/
    - assets/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
